### ISSUE TITLE
Undefined property: stdClass::$channel

### ISSUE THREAD

**Issue by Oxygenism** [Piggy-Loyalty/piggy-php-sdk#27] opened 2024-05-08 15:34 UTC
When trying to create a new credit reception, the following error occurs. 
```
Warning: Undefined property: stdClass::$channel in vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php on line 52 
 #0 vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php(52): Magento\Framework\App\ErrorHandler->handler(2, 'Undefined prope...', '..', 52)
#1 vendor/piggy/piggy-php-sdk/src/Resources/OAuth/Loyalty/Receptions/CreditReceptionsResource.php(47): Piggy\Api\Mappers\Loyalty\Receptions\CreditReceptionMapper->map(Object(stdClass))
#2 app/code/Bold/PiggyIntegration/Model/Type/Credit/Transaction.php(70): Piggy\Api\Resources\OAuth\Loyalty\Receptions\CreditReceptionsResource->create('<uuid>..', '<uuid>...', 19.98, 20, NULL, NULL, NULL, Array)
```
Due to, I assume, no channel existing during creation. I fixed it by applying the following patch:

```
Index: vendor/piggy/piggy-php-sdk/src/Models/Loyalty/Receptions/CreditReception.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/piggy/piggy-php-sdk/src/Models/Loyalty/Receptions/CreditReception.php b/vendor/piggy/piggy-php-sdk/src/Models/Loyalty/Receptions/CreditReception.php
--- a/vendor/piggy/piggy-php-sdk/src/Models/Loyalty/Receptions/CreditReception.php	
+++ b/vendor/piggy/piggy-php-sdk/src/Models/Loyalty/Receptions/CreditReception.php	(date 1715182204703)
@@ -73,7 +73,7 @@
     /**
      * @param  mixed[]  $attributes
      */
-    public function __construct(string $type, int $credits, string $uuid, ?Contact $contact, ?Shop $shop, string $channel, ?ContactIdentifier $contactIdentifier, DateTime $createdAt, ?float $unitValue = null, ?Unit $unit = null, array $attributes = [])
+    public function __construct(string $type, int $credits, string $uuid, ?Contact $contact, ?Shop $shop, ?string $channel, ?ContactIdentifier $contactIdentifier, DateTime $createdAt, ?float $unitValue = null, ?Unit $unit = null, array $attributes = [])
     {
         $this->type = $type;
         $this->credits = $credits;
Index: vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php b/vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php
--- a/vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php	
+++ b/vendor/piggy/piggy-php-sdk/src/Mappers/Loyalty/Receptions/CreditReceptionMapper.php	(date 1715181962609)
@@ -49,7 +49,7 @@
             $data->uuid,
             $contact ?? null,
             $shop ?? null,
-            $data->channel,
+            $data->channel ?? null,
             $contactIdentifier ?? null,
             $this->parseDate($data->created_at),
             $data->unit_value ?? null,
```

Thanks :)

**Comment by iDiegoNL** [comment] 2024-05-08 19:52
Thanks for reporting this issue!

The channel always exists, also on creation (when creating via the API, the channel is `OAUTH_API`). The issue is that we in the API currently only return a channel for loyalty transactions, not yet for credit & reward receptions.

I currently have an internal PR with the fix ready, but keep in mind that it might take a bit longer due to the Dutch holiday & then the weekend. Will keep this issue up-to-date once it's fixed!

**Comment by Oxygenism** [comment] 2024-05-09 05:39
Alright, thanks for notifying me of the actual cause! 
That probably means I'll have to look into any duplicated credit receptions that might've been created due to this issue. As they weren't marked as processed in my system.

**Comment by iDiegoNL** [comment] 2024-05-09 18:50
This should be fixed since this morning. Let me know if you still have any issues! :)

**Closed as completed by iDiegoNL** 2024-05-09 18:50 UTC
